// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrcfubwnvvhjcvxdwrhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yY2Z1YndudnZoamN2eGR3cmhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTYzMjksImV4cCI6MjA2MjE5MjMyOX0.1CsnZGm-VapqRhPGkEkKrU6blhj538MtGS7S0GDjr8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);